export const AFRICAN_CURRENCIES = [
  { code: 'USD', symbol: '$',    name: 'US Dollar (Universal)' },
  { code: 'NGN', symbol: '₦',   name: 'Nigerian Naira' },
  { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling' },
  { code: 'GHS', symbol: 'GH₵', name: 'Ghanaian Cedi' },
  { code: 'ZAR', symbol: 'R',   name: 'South African Rand' },
  { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling' },
  { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling' },
  { code: 'ETB', symbol: 'Br',  name: 'Ethiopian Birr' },
  { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  { code: 'XAF', symbol: 'CFA', name: 'Central African CFA Franc' },
  { code: 'MAD', symbol: 'MAD', name: 'Moroccan Dirham' },
  { code: 'EGP', symbol: 'E£',  name: 'Egyptian Pound' },
  { code: 'DZD', symbol: 'DA',  name: 'Algerian Dinar' },
  { code: 'TND', symbol: 'DT',  name: 'Tunisian Dinar' },
  { code: 'LYD', symbol: 'LD',  name: 'Libyan Dinar' },
  { code: 'RWF', symbol: 'FRw', name: 'Rwandan Franc' },
  { code: 'MZN', symbol: 'MT',  name: 'Mozambican Metical' },
  { code: 'BWP', symbol: 'P',   name: 'Botswanan Pula' },
  { code: 'ZMW', symbol: 'ZK',  name: 'Zambian Kwacha' },
  { code: 'AOA', symbol: 'Kz',  name: 'Angolan Kwanza' },
  { code: 'CDF', symbol: 'FC',  name: 'Congolese Franc' },
  { code: 'MGA', symbol: 'Ar',  name: 'Malagasy Ariary' },
  { code: 'MWK', symbol: 'MK',  name: 'Malawian Kwacha' },
  { code: 'NAD', symbol: 'N$',  name: 'Namibian Dollar' },
  { code: 'SZL', symbol: 'L',   name: 'Swazi Lilangeni' },
  { code: 'SLL', symbol: 'Le',  name: 'Sierra Leonean Leone' },
  { code: 'GMD', symbol: 'D',   name: 'Gambian Dalasi' },
  { code: 'MUR', symbol: '₨',   name: 'Mauritian Rupee' },
  { code: 'SDG', symbol: 'SDG', name: 'Sudanese Pound' },
  { code: 'SOS', symbol: 'Sh',  name: 'Somali Shilling' },
] as const

export type CurrencyCode = typeof AFRICAN_CURRENCIES[number]['code']

export function getCurrencySymbol(code: string | null | undefined): string {
  if (!code) return '$'
  return AFRICAN_CURRENCIES.find(c => c.code === code)?.symbol ?? code
}

export function formatPrice(price: number, currencyCode: string | null | undefined): string {
  return `${getCurrencySymbol(currencyCode)}${price.toLocaleString()}`
}

export const AFRICAN_COUNTRIES = [
  { name: 'Algeria',                  flag: '🇩🇿' },
  { name: 'Angola',                   flag: '🇦🇴' },
  { name: 'Benin',                    flag: '🇧🇯' },
  { name: 'Botswana',                 flag: '🇧🇼' },
  { name: 'Burkina Faso',             flag: '🇧🇫' },
  { name: 'Burundi',                  flag: '🇧🇮' },
  { name: 'Cameroon',                 flag: '🇨🇲' },
  { name: 'Cape Verde',               flag: '🇨🇻' },
  { name: 'Central African Republic', flag: '🇨🇫' },
  { name: 'Chad',                     flag: '🇹🇩' },
  { name: 'Comoros',                  flag: '🇰🇲' },
  { name: 'DR Congo',                 flag: '🇨🇩' },
  { name: 'Republic of Congo',        flag: '🇨🇬' },
  { name: 'Djibouti',                 flag: '🇩🇯' },
  { name: 'Egypt',                    flag: '🇪🇬' },
  { name: 'Equatorial Guinea',        flag: '🇬🇶' },
  { name: 'Eritrea',                  flag: '🇪🇷' },
  { name: 'Eswatini',                 flag: '🇸🇿' },
  { name: 'Ethiopia',                 flag: '🇪🇹' },
  { name: 'Gabon',                    flag: '🇬🇦' },
  { name: 'Gambia',                   flag: '🇬🇲' },
  { name: 'Ghana',                    flag: '🇬🇭' },
  { name: 'Guinea',                   flag: '🇬🇳' },
  { name: 'Guinea-Bissau',            flag: '🇬🇼' },
  { name: 'Ivory Coast',              flag: '🇨🇮' },
  { name: 'Kenya',                    flag: '🇰🇪' },
  { name: 'Lesotho',                  flag: '🇱🇸' },
  { name: 'Liberia',                  flag: '🇱🇷' },
  { name: 'Libya',                    flag: '🇱🇾' },
  { name: 'Madagascar',               flag: '🇲🇬' },
  { name: 'Malawi',                   flag: '🇲🇼' },
  { name: 'Mali',                     flag: '🇲🇱' },
  { name: 'Mauritania',               flag: '🇲🇷' },
  { name: 'Mauritius',                flag: '🇲🇺' },
  { name: 'Morocco',                  flag: '🇲🇦' },
  { name: 'Mozambique',               flag: '🇲🇿' },
  { name: 'Namibia',                  flag: '🇳🇦' },
  { name: 'Niger',                    flag: '🇳🇪' },
  { name: 'Nigeria',                  flag: '🇳🇬' },
  { name: 'Rwanda',                   flag: '🇷🇼' },
  { name: 'São Tomé & Príncipe',      flag: '🇸🇹' },
  { name: 'Senegal',                  flag: '🇸🇳' },
  { name: 'Seychelles',               flag: '🇸🇨' },
  { name: 'Sierra Leone',             flag: '🇸🇱' },
  { name: 'Somalia',                  flag: '🇸🇴' },
  { name: 'South Africa',             flag: '🇿🇦' },
  { name: 'South Sudan',              flag: '🇸🇸' },
  { name: 'Sudan',                    flag: '🇸🇩' },
  { name: 'Tanzania',                 flag: '🇹🇿' },
  { name: 'Togo',                     flag: '🇹🇬' },
  { name: 'Tunisia',                  flag: '🇹🇳' },
  { name: 'Uganda',                   flag: '🇺🇬' },
  { name: 'Zambia',                   flag: '🇿🇲' },
  { name: 'Zimbabwe',                 flag: '🇿🇼' },
] as const
